apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rj81k55d7-java-quarkus 
  description: Secure Supply Chain Example for Quarkus Java example with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=rj81k55d7-java-quarkus
    backstage.io/kubernetes-id: rj81k55d7-java-quarkus 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: rj81k55d7-java-quarkus
    nexus-repository-manager/docker.image-name: rhtap/rhtap-qe-java-quarkus
  tags: ["java", "quarkus", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 